export type Alumno = {
  id: number;
  primerApellido: string;
  segundoApellido: string;
  nombre: string;
  rut: string;
  telefono: string;
  correo: string;
  nombreEmergencia: string;
  telefonoEmergencia: string;
  institucion: "INACAP";
};

export const data: Alumno[] = [
  {
    id: 1,
    primerApellido: "Labbé",
    segundoApellido: "Zúñiga",
    nombre: "Karla Estrella",
    rut: "20.963.728-6",
    telefono: "966 599 330",
    correo: "karla.labbe@inacapmail.cl",
    nombreEmergencia: "Susy Zúñiga",
    telefonoEmergencia: "989 022 154",
    institucion: "INACAP",
  },
  {
    id: 2,
    primerApellido: "Burgos",
    segundoApellido: "Rios",
    nombre: "Alexis Andrés",
    rut: "20.443.124-8",
    telefono: "977 947 138",
    correo: "alexis.burgos@inacapmail.cl",
    nombreEmergencia: "Rigoberto Burgos",
    telefonoEmergencia: "933 976 968",
    institucion: "INACAP",
  },
  {
    id: 3,
    primerApellido: "Carroza",
    segundoApellido: "Barahona",
    nombre: "Lucas Nicolás",
    rut: "20.397.829-4",
    telefono: "984 603 267",
    correo: "lucas.barahona@inacapmail.cl",
    nombreEmergencia: "Edita Carroza",
    telefonoEmergencia: "961 336 642",
    institucion: "INACAP",
  },
  {
    id: 4,
    primerApellido: "Duarte",
    segundoApellido: "Cortez",
    nombre: "María Ignacia",
    rut: "20.726.668-4",
    telefono: "966 906 660",
    correo: "mariai.duarte@inacapmail.cl",
    nombreEmergencia: "María Elena Cortez",
    telefonoEmergencia: "999 383 771",
    institucion: "INACAP",
  },
  {
    id: 5,
    primerApellido: "Gallardo",
    segundoApellido: "Rojas",
    nombre: "Sofía Ester",
    rut: "20.481.541-0",
    telefono: "990 719 587",
    correo: "sofia.gallardo@inacapmail.cl",
    nombreEmergencia: "Susana Rojas",
    telefonoEmergencia: "962 293 274",
    institucion: "INACAP",
  },
  {
    id: 6,
    primerApellido: "Pérez",
    segundoApellido: "Gómez",
    nombre: "Juan Pablo",
    rut: "20.111.222-3",
    telefono: "912 345 678",
    correo: "juan.perez@inacapmail.cl",
    nombreEmergencia: "Ana Gómez",
    telefonoEmergencia: "912 345 679",
    institucion: "INACAP",
  },
  {
    id: 7,
    primerApellido: "Soto",
    segundoApellido: "Muñoz",
    nombre: "Camila Andrea",
    rut: "20.222.333-4",
    telefono: "913 456 789",
    correo: "camila.soto@inacapmail.cl",
    nombreEmergencia: "Pedro Muñoz",
    telefonoEmergencia: "913 456 780",
    institucion: "INACAP",
  },
  {
    id: 8,
    primerApellido: "Vega",
    segundoApellido: "López",
    nombre: "Matías Ignacio",
    rut: "20.333.444-5",
    telefono: "914 567 890",
    correo: "matias.vega@inacapmail.cl",
    nombreEmergencia: "Laura López",
    telefonoEmergencia: "914 567 891",
    institucion: "INACAP",
  },
  {
    id: 9,
    primerApellido: "Ramírez",
    segundoApellido: "Castro",
    nombre: "Valentina Paz",
    rut: "20.444.555-6",
    telefono: "915 678 901",
    correo: "valentina.ramirez@inacapmail.cl",
    nombreEmergencia: "Carlos Castro",
    telefonoEmergencia: "915 678 902",
    institucion: "INACAP",
  },
  {
    id: 10,
    primerApellido: "Torres",
    segundoApellido: "Silva",
    nombre: "Diego Alejandro",
    rut: "20.555.666-7",
    telefono: "916 789 012",
    correo: "diego.torres@inacapmail.cl",
    nombreEmergencia: "María Silva",
    telefonoEmergencia: "916 789 013",
    institucion: "INACAP",
  },
  {
    id: 11,
    primerApellido: "Morales",
    segundoApellido: "Reyes",
    nombre: "Fernanda Belén",
    rut: "20.666.777-8",
    telefono: "917 890 123",
    correo: "fernanda.morales@inacapmail.cl",
    nombreEmergencia: "Jorge Reyes",
    telefonoEmergencia: "917 890 124",
    institucion: "INACAP",
  },
  {
    id: 12,
    primerApellido: "Fuentes",
    segundoApellido: "Herrera",
    nombre: "Tomás Eduardo",
    rut: "20.777.888-9",
    telefono: "918 901 234",
    correo: "tomas.fuentes@inacapmail.cl",
    nombreEmergencia: "Patricia Herrera",
    telefonoEmergencia: "918 901 235",
    institucion: "INACAP",
  },
  {
    id: 13,
    primerApellido: "Navarro",
    segundoApellido: "Molina",
    nombre: "Josefa Antonia",
    rut: "20.888.999-0",
    telefono: "919 012 345",
    correo: "josefa.navarro@inacapmail.cl",
    nombreEmergencia: "Ricardo Molina",
    telefonoEmergencia: "919 012 346",
    institucion: "INACAP",
  },
  {
    id: 14,
    primerApellido: "Rojas",
    segundoApellido: "Vargas",
    nombre: "Cristóbal Andrés",
    rut: "20.999.000-1",
    telefono: "920 123 456",
    correo: "cristobal.rojas@inacapmail.cl",
    nombreEmergencia: "Andrea Vargas",
    telefonoEmergencia: "920 123 457",
    institucion: "INACAP",
  },
  {
    id: 15,
    primerApellido: "Gutiérrez",
    segundoApellido: "Sánchez",
    nombre: "Daniela Sofía",
    rut: "21.000.111-2",
    telefono: "921 234 567",
    correo: "daniela.gutierrez@inacapmail.cl",
    nombreEmergencia: "Luis Sánchez",
    telefonoEmergencia: "921 234 568",
    institucion: "INACAP",
  },
  {
    id: 16,
    primerApellido: "Castillo",
    segundoApellido: "Cáceres",
    nombre: "Ignacio Javier",
    rut: "21.111.222-3",
    telefono: "922 345 678",
    correo: "ignacio.castillo@inacapmail.cl",
    nombreEmergencia: "Marcela Cáceres",
    telefonoEmergencia: "922 345 679",
    institucion: "INACAP",
  },
  {
    id: 17,
    primerApellido: "Silva",
    segundoApellido: "Pizarro",
    nombre: "Antonia Isidora",
    rut: "21.222.333-4",
    telefono: "923 456 789",
    correo: "antonia.silva@inacapmail.cl",
    nombreEmergencia: "Javier Pizarro",
    telefonoEmergencia: "923 456 790",
    institucion: "INACAP",
  },
  {
    id: 18,
    primerApellido: "Martínez",
    segundoApellido: "Araya",
    nombre: "Benjamín Alonso",
    rut: "21.333.444-5",
    telefono: "924 567 890",
    correo: "benjamin.martinez@inacapmail.cl",
    nombreEmergencia: "Claudia Araya",
    telefonoEmergencia: "924 567 891",
    institucion: "INACAP",
  },
  {
    id: 19,
    primerApellido: "López",
    segundoApellido: "Espinoza",
    nombre: "Florencia Emilia",
    rut: "21.444.555-6",
    telefono: "925 678 901",
    correo: "florencia.lopez@inacapmail.cl",
    nombreEmergencia: "Gonzalo Espinoza",
    telefonoEmergencia: "925 678 902",
    institucion: "INACAP",
  },
  {
    id: 20,
    primerApellido: "Reyes",
    segundoApellido: "Salazar",
    nombre: "Vicente Tomás",
    rut: "21.555.666-7",
    telefono: "926 789 012",
    correo: "vicente.reyes@inacapmail.cl",
    nombreEmergencia: "Paula Salazar",
    telefonoEmergencia: "926 789 013",
    institucion: "INACAP",
  },
  {
    id: 21,
    primerApellido: "Muñoz",
    segundoApellido: "Moreno",
    nombre: "Martina Josefa",
    rut: "21.666.777-8",
    telefono: "927 890 123",
    correo: "martina.munoz@inacapmail.cl",
    nombreEmergencia: "Rodrigo Moreno",
    telefonoEmergencia: "927 890 124",
    institucion: "INACAP",
  },
  {
    id: 22,
    primerApellido: "González",
    segundoApellido: "Riquelme",
    nombre: "Joaquín Esteban",
    rut: "21.777.888-9",
    telefono: "928 901 234",
    correo: "joaquin.gonzalez@inacapmail.cl",
    nombreEmergencia: "Teresa Riquelme",
    telefonoEmergencia: "928 901 235",
    institucion: "INACAP",
  },
  {
    id: 23,
    primerApellido: "Díaz",
    segundoApellido: "Bravo",
    nombre: "Amanda Catalina",
    rut: "21.888.999-0",
    telefono: "929 012 345",
    correo: "amanda.diaz@inacapmail.cl",
    nombreEmergencia: "Felipe Bravo",
    telefonoEmergencia: "929 012 346",
    institucion: "INACAP",
  },
  {
    id: 24,
    primerApellido: "Ramos",
    segundoApellido: "Saavedra",
    nombre: "Emilia Fernanda",
    rut: "21.999.000-1",
    telefono: "930 123 456",
    correo: "emilia.ramos@inacapmail.cl",
    nombreEmergencia: "Gabriel Saavedra",
    telefonoEmergencia: "930 123 457",
    institucion: "INACAP",
  },
  {
    id: 25,
    primerApellido: "Cárdenas",
    segundoApellido: "Campos",
    nombre: "Leonardo David",
    rut: "22.000.111-2",
    telefono: "931 234 567",
    correo: "leonardo.cardenas@inacapmail.cl",
    nombreEmergencia: "Verónica Campos",
    telefonoEmergencia: "931 234 568",
    institucion: "INACAP",
  },
  {
    id: 26,
    primerApellido: "Pizarro",
    segundoApellido: "Maldonado",
    nombre: "Josefina Paz",
    rut: "22.111.222-3",
    telefono: "932 345 678",
    correo: "josefina.pizarro@inacapmail.cl",
    nombreEmergencia: "Héctor Maldonado",
    telefonoEmergencia: "932 345 679",
    institucion: "INACAP",
  },
  {
    id: 27,
    primerApellido: "Bravo",
    segundoApellido: "Carrasco",
    nombre: "Gabriel Ignacio",
    rut: "22.222.333-4",
    telefono: "933 456 789",
    correo: "gabriel.bravo@inacapmail.cl",
    nombreEmergencia: "Lorena Carrasco",
    telefonoEmergencia: "933 456 790",
    institucion: "INACAP",
  },
  {
    id: 28,
    primerApellido: "Saavedra",
    segundoApellido: "Ortega",
    nombre: "Renata Alejandra",
    rut: "22.333.444-5",
    telefono: "934 567 890",
    correo: "renata.saavedra@inacapmail.cl",
    nombreEmergencia: "Cristian Ortega",
    telefonoEmergencia: "934 567 891",
    institucion: "INACAP",
  },
  {
    id: 29,
    primerApellido: "Campos",
    segundoApellido: "Garrido",
    nombre: "Vicente Andrés",
    rut: "22.444.555-6",
    telefono: "935 678 901",
    correo: "vicente.campos@inacapmail.cl",
    nombreEmergencia: "Pamela Garrido",
    telefonoEmergencia: "935 678 902",
    institucion: "INACAP",
  },
  {
    id: 30,
    primerApellido: "Maldonado",
    segundoApellido: "Navarrete",
    nombre: "Isidora Belén",
    rut: "22.555.666-7",
    telefono: "936 789 012",
    correo: "isidora.maldonado@inacapmail.cl",
    nombreEmergencia: "Juan Navarrete",
    telefonoEmergencia: "936 789 013",
    institucion: "INACAP",
  },
  {
    id: 31,
    primerApellido: "Carrasco",
    segundoApellido: "Vergara",
    nombre: "Agustín Matías",
    rut: "22.666.777-8",
    telefono: "937 890 123",
    correo: "agustin.carrasco@inacapmail.cl",
    nombreEmergencia: "Cecilia Vergara",
    telefonoEmergencia: "937 890 124",
    institucion: "INACAP",
  },
  {
    id: 32,
    primerApellido: "Ortega",
    segundoApellido: "Tapia",
    nombre: "Florencia Antonia",
    rut: "22.777.888-9",
    telefono: "938 901 234",
    correo: "florencia.ortega@inacapmail.cl",
    nombreEmergencia: "Alfredo Tapia",
    telefonoEmergencia: "938 901 235",
    institucion: "INACAP",
  },
  {
    id: 33,
    primerApellido: "Garrido",
    segundoApellido: "Aguilera",
    nombre: "Lucas Benjamín",
    rut: "22.888.999-0",
    telefono: "939 012 345",
    correo: "lucas.garrido@inacapmail.cl",
    nombreEmergencia: "Patricia Aguilera",
    telefonoEmergencia: "939 012 346",
    institucion: "INACAP",
  },
  {
    id: 34,
    primerApellido: "Navarrete",
    segundoApellido: "Parra",
    nombre: "Amanda Isidora",
    rut: "22.999.000-1",
    telefono: "940 123 456",
    correo: "amanda.navarrete@inacapmail.cl",
    nombreEmergencia: "Rodrigo Parra",
    telefonoEmergencia: "940 123 457",
    institucion: "INACAP",
  },
  {
    id: 35,
    primerApellido: "Vergara",
    segundoApellido: "Romero",
    nombre: "Martín Alejandro",
    rut: "23.000.111-2",
    telefono: "941 234 567",
    correo: "martin.vergara@inacapmail.cl",
    nombreEmergencia: "María Romero",
    telefonoEmergencia: "941 234 568",
    institucion: "INACAP",
  },
  {
    id: 36,
    primerApellido: "Tapia",
    segundoApellido: "Miranda",
    nombre: "Josefa Fernanda",
    rut: "23.111.222-3",
    telefono: "942 345 678",
    correo: "josefa.tapia@inacapmail.cl",
    nombreEmergencia: "Sergio Miranda",
    telefonoEmergencia: "942 345 679",
    institucion: "INACAP",
  },
  {
    id: 37,
    primerApellido: "Aguilera",
    segundoApellido: "Rivas",
    nombre: "Tomás Sebastián",
    rut: "23.222.333-4",
    telefono: "943 456 789",
    correo: "tomas.aguilera@inacapmail.cl",
    nombreEmergencia: "Paula Rivas",
    telefonoEmergencia: "943 456 790",
    institucion: "INACAP",
  },
  {
    id: 38,
    primerApellido: "Parra",
    segundoApellido: "Escobar",
    nombre: "Valentina Andrea",
    rut: "23.333.444-5",
    telefono: "944 567 890",
    correo: "valentina.parra@inacapmail.cl",
    nombreEmergencia: "Gonzalo Escobar",
    telefonoEmergencia: "944 567 891",
    institucion: "INACAP",
  },
  {
    id: 39,
    primerApellido: "Romero",
    segundoApellido: "Medina",
    nombre: "Emilia Josefa",
    rut: "23.444.555-6",
    telefono: "945 678 901",
    correo: "emilia.romero@inacapmail.cl",
    nombreEmergencia: "Andrea Medina",
    telefonoEmergencia: "945 678 902",
    institucion: "INACAP",
  },
  {
    id: 40,
    primerApellido: "Miranda",
    segundoApellido: "Vidal",
    nombre: "Benjamín Nicolás",
    rut: "23.555.666-7",
    telefono: "946 789 012",
    correo: "benjamin.miranda@inacapmail.cl",
    nombreEmergencia: "Claudia Vidal",
    telefonoEmergencia: "946 789 013",
    institucion: "INACAP",
  },
  {
    id: 41,
    primerApellido: "Rivas",
    segundoApellido: "Sanhueza",
    nombre: "Sofía Antonia",
    rut: "23.666.777-8",
    telefono: "947 890 123",
    correo: "sofia.rivas@inacapmail.cl",
    nombreEmergencia: "Jorge Sanhueza",
    telefonoEmergencia: "947 890 124",
    institucion: "INACAP",
  },
  {
    id: 42,
    primerApellido: "Escobar",
    segundoApellido: "Godoy",
    nombre: "Vicente Gabriel",
    rut: "23.777.888-9",
    telefono: "948 901 234",
    correo: "vicente.escobar@inacapmail.cl",
    nombreEmergencia: "Teresa Godoy",
    telefonoEmergencia: "948 901 235",
    institucion: "INACAP",
  },
  {
    id: 43,
    primerApellido: "Medina",
    segundoApellido: "Peña",
    nombre: "Martina Valentina",
    rut: "23.888.999-0",
    telefono: "949 012 345",
    correo: "martina.medina@inacapmail.cl",
    nombreEmergencia: "Felipe Peña",
    telefonoEmergencia: "949 012 346",
    institucion: "INACAP",
  },
  {
    id: 44,
    primerApellido: "Vidal",
    segundoApellido: "Figueroa",
    nombre: "Joaquín Matías",
    rut: "23.999.000-1",
    telefono: "950 123 456",
    correo: "joaquin.vidal@inacapmail.cl",
    nombreEmergencia: "Pamela Figueroa",
    telefonoEmergencia: "950 123 457",
    institucion: "INACAP",
  },
  {
    id: 45,
    primerApellido: "Sanhueza",
    segundoApellido: "Lagos",
    nombre: "Josefa Emilia",
    rut: "24.000.111-2",
    telefono: "951 234 567",
    correo: "josefa.sanhueza@inacapmail.cl",
    nombreEmergencia: "Rodrigo Lagos",
    telefonoEmergencia: "951 234 568",
    institucion: "INACAP",
  },
  {
    id: 46,
    primerApellido: "Godoy",
    segundoApellido: "Toledo",
    nombre: "Tomás Vicente",
    rut: "24.111.222-3",
    telefono: "952 345 678",
    correo: "tomas.godoy@inacapmail.cl",
    nombreEmergencia: "Verónica Toledo",
    telefonoEmergencia: "952 345 679",
    institucion: "INACAP",
  },
  {
    id: 47,
    primerApellido: "Peña",
    segundoApellido: "Cifuentes",
    nombre: "Florencia Amanda",
    rut: "24.222.333-4",
    telefono: "953 456 789",
    correo: "florencia.pena@inacapmail.cl",
    nombreEmergencia: "Héctor Cifuentes",
    telefonoEmergencia: "953 456 790",
    institucion: "INACAP",
  },
  {
    id: 48,
    primerApellido: "Figueroa",
    segundoApellido: "Salinas",
    nombre: "Lucas Joaquín",
    rut: "24.333.444-5",
    telefono: "954 567 890",
    correo: "lucas.figueroa@inacapmail.cl",
    nombreEmergencia: "Lorena Salinas",
    telefonoEmergencia: "954 567 891",
    institucion: "INACAP",
  },
  {
    id: 49,
    primerApellido: "Lagos",
    segundoApellido: "Castro",
    nombre: "Emilia Josefa",
    rut: "24.444.555-6",
    telefono: "955 678 901",
    correo: "emilia.lagos@inacapmail.cl",
    nombreEmergencia: "Gabriel Castro",
    telefonoEmergencia: "955 678 902",
    institucion: "INACAP",
  },
  {
    id: 50,
    primerApellido: "Toledo",
    segundoApellido: "Soto",
    nombre: "Vicente Martín",
    rut: "24.555.666-7",
    telefono: "956 789 012",
    correo: "vicente.toledo@inacapmail.cl",
    nombreEmergencia: "Cecilia Soto",
    telefonoEmergencia: "956 789 013",
    institucion: "INACAP",
  }
];