export type Alumno = {
  id: number;
  primerApellido: string;
  segundoApellido: string;
  nombre: string;
  rut: string;
  telefono: string;
  correo: string;
  nombreEmergencia: string;
  telefonoEmergencia: string;
  institucion: string;
};

export const nombreServicio = "Medicina";

export type EstadoRotacion = "Programada" | "En Curso" | "Finalizada";

export type RotacionServicio = {
  id: string;
  centroFormador: string;
  carrera: string;
  fechaInicio: string;
  fechaTermino: string;
  numeroAlumnos: number;
  tipoJornada: string;
  asignatura?: string | null;
  estado: EstadoRotacion;
  alumnosAsignados: Alumno[];
};

export const data: RotacionServicio[] = [
  {
    id: "NOM-2025-001",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "03/03/2025",
    fechaTermino: "12/04/2025",
    numeroAlumnos: 2,
    tipoJornada: "Diurna",
    asignatura: "Salud del Adulto I",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 1,
        nombre: "Karla Estrella",
        primerApellido: "Labbé",
        segundoApellido: "Zúñiga",
        rut: "20.963.728-6",
        correo: "k.labbe@inacapmail.cl",
        telefono: "966599330",
        nombreEmergencia: "Susy Z",
        telefonoEmergencia: "989022154",
        institucion: "INACAP",
      },
      {
        id: 2,
        nombre: "Alexis Andrés",
        primerApellido: "Burgos",
        segundoApellido: "Rios",
        rut: "20.443.124-8",
        correo: "a.burgos@inacapmail.cl",
        telefono: "977947138",
        nombreEmergencia: "Rigoberto B",
        telefonoEmergencia: "933976968",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-015",
    centroFormador: "Universidad de O'Higgins",
    carrera: "Medicina",
    fechaInicio: "18/08/2025",
    fechaTermino: "27/09/2025",
    numeroAlumnos: 6,
    tipoJornada: "4 Turno",
    asignatura: "Internado Medicina Interna",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 10,
        nombre: "Diego Alejandro",
        primerApellido: "Torres",
        segundoApellido: "Silva",
        rut: "20.555.666-7",
        correo: "d.torres@uoh.cl",
        telefono: "916789012",
        nombreEmergencia: "María S",
        telefonoEmergencia: "916789013",
        institucion: "UOH",
      },
      {
        id: 11,
        nombre: "Fernanda Belén",
        primerApellido: "Morales",
        segundoApellido: "Reyes",
        rut: "20.666.777-8",
        correo: "f.morales@uoh.cl",
        telefono: "917890123",
        nombreEmergencia: "Jorge R",
        telefonoEmergencia: "917890124",
        institucion: "UOH",
      },
      {
        id: 12,
        nombre: "Tomás Eduardo",
        primerApellido: "Fuentes",
        segundoApellido: "Herrera",
        rut: "20.777.888-9",
        correo: "t.fuentes@uoh.cl",
        telefono: "918901234",
        nombreEmergencia: "Patricia H",
        telefonoEmergencia: "918901235",
        institucion: "UOH",
      },
      {
        id: 13,
        nombre: "Josefa Antonia",
        primerApellido: "Navarro",
        segundoApellido: "Molina",
        rut: "20.888.999-0",
        correo: "j.navarro@uoh.cl",
        telefono: "919012345",
        nombreEmergencia: "Ricardo M",
        telefonoEmergencia: "919012346",
        institucion: "UOH",
      },
      {
        id: 14,
        nombre: "Cristóbal Andrés",
        primerApellido: "Rojas",
        segundoApellido: "Vargas",
        rut: "20.999.000-1",
        correo: "c.rojas@uoh.cl",
        telefono: "920123456",
        nombreEmergencia: "Andrea V",
        telefonoEmergencia: "920123457",
        institucion: "UOH",
      },
      {
        id: 15,
        nombre: "Daniela Sofía",
        primerApellido: "Gutiérrez",
        segundoApellido: "Sánchez",
        rut: "21.000.111-2",
        correo: "d.gutierrez@uoh.cl",
        telefono: "921234567",
        nombreEmergencia: "Luis S",
        telefonoEmergencia: "921234568",
        institucion: "UOH",
      },
    ],
  },
  {
    id: "NOM-2025-022",
    centroFormador: "AIEP",
    carrera: "Enfermería",
    fechaInicio: "15/10/2025",
    fechaTermino: "22/11/2025",
    numeroAlumnos: 4,
    tipoJornada: "Diurna",
    asignatura: "Cuidados del Adulto",
    estado: "En Curso",
    alumnosAsignados: [
      {
        id: 16,
        nombre: "Ignacio Javier",
        primerApellido: "Castillo",
        segundoApellido: "Cáceres",
        rut: "21.111.222-3",
        correo: "i.castillo@aiep.cl",
        telefono: "922345678",
        nombreEmergencia: "Marcela C",
        telefonoEmergencia: "922345679",
        institucion: "AIEP",
      },
      {
        id: 17,
        nombre: "Antonia Isidora",
        primerApellido: "Silva",
        segundoApellido: "Pizarro",
        rut: "21.222.333-4",
        correo: "a.silva@aiep.cl",
        telefono: "923456789",
        nombreEmergencia: "Javier P",
        telefonoEmergencia: "923456790",
        institucion: "AIEP",
      },
      {
        id: 18,
        nombre: "Benjamín Alonso",
        primerApellido: "Martínez",
        segundoApellido: "Araya",
        rut: "21.333.444-5",
        correo: "b.martinez@aiep.cl",
        telefono: "924567890",
        nombreEmergencia: "Claudia A",
        telefonoEmergencia: "924567891",
        institucion: "AIEP",
      },
      {
        id: 19,
        nombre: "Florencia Emilia",
        primerApellido: "López",
        segundoApellido: "Espinoza",
        rut: "21.444.555-6",
        correo: "f.lopez@aiep.cl",
        telefono: "925678901",
        nombreEmergencia: "Gonzalo E",
        telefonoEmergencia: "925678902",
        institucion: "AIEP",
      },
    ],
  },
  {
    id: "NOM-2025-030",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "27/10/2025",
    fechaTermino: "06/12/2025",
    numeroAlumnos: 3,
    tipoJornada: "Diurna",
    asignatura: "Procedimientos Básicos",
    estado: "Programada",
    alumnosAsignados: [
      {
        id: 20,
        nombre: "Vicente Tomás",
        primerApellido: "Reyes",
        segundoApellido: "Salazar",
        rut: "21.555.666-7",
        correo: "v.reyes@inacapmail.cl",
        telefono: "926789012",
        nombreEmergencia: "Paula S",
        telefonoEmergencia: "926789013",
        institucion: "INACAP",
      },
      {
        id: 21,
        nombre: "Martina Josefa",
        primerApellido: "Muñoz",
        segundoApellido: "Moreno",
        rut: "21.666.777-8",
        correo: "m.munoz@inacapmail.cl",
        telefono: "927890123",
        nombreEmergencia: "Rodrigo M",
        telefonoEmergencia: "927890124",
        institucion: "INACAP",
      },
      {
        id: 22,
        nombre: "Joaquín Esteban",
        primerApellido: "González",
        segundoApellido: "Riquelme",
        rut: "21.777.888-9",
        correo: "j.gonzalez@inacapmail.cl",
        telefono: "928901234",
        nombreEmergencia: "Teresa R",
        telefonoEmergencia: "928901235",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-001",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "03/03/2025",
    fechaTermino: "12/04/2025",
    numeroAlumnos: 2,
    tipoJornada: "Diurna",
    asignatura: "Salud del Adulto I",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 1,
        nombre: "Karla Estrella",
        primerApellido: "Labbé",
        segundoApellido: "Zúñiga",
        rut: "20.963.728-6",
        correo: "k.labbe@inacapmail.cl",
        telefono: "966599330",
        nombreEmergencia: "Susy Z",
        telefonoEmergencia: "989022154",
        institucion: "INACAP",
      },
      {
        id: 2,
        nombre: "Alexis Andrés",
        primerApellido: "Burgos",
        segundoApellido: "Rios",
        rut: "20.443.124-8",
        correo: "a.burgos@inacapmail.cl",
        telefono: "977947138",
        nombreEmergencia: "Rigoberto B",
        telefonoEmergencia: "933976968",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-015",
    centroFormador: "Universidad de O'Higgins",
    carrera: "Medicina",
    fechaInicio: "18/08/2025",
    fechaTermino: "27/09/2025",
    numeroAlumnos: 6,
    tipoJornada: "4 Turno",
    asignatura: "Internado Medicina Interna",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 10,
        nombre: "Diego Alejandro",
        primerApellido: "Torres",
        segundoApellido: "Silva",
        rut: "20.555.666-7",
        correo: "d.torres@uoh.cl",
        telefono: "916789012",
        nombreEmergencia: "María S",
        telefonoEmergencia: "916789013",
        institucion: "UOH",
      },
      {
        id: 11,
        nombre: "Fernanda Belén",
        primerApellido: "Morales",
        segundoApellido: "Reyes",
        rut: "20.666.777-8",
        correo: "f.morales@uoh.cl",
        telefono: "917890123",
        nombreEmergencia: "Jorge R",
        telefonoEmergencia: "917890124",
        institucion: "UOH",
      },
      {
        id: 12,
        nombre: "Tomás Eduardo",
        primerApellido: "Fuentes",
        segundoApellido: "Herrera",
        rut: "20.777.888-9",
        correo: "t.fuentes@uoh.cl",
        telefono: "918901234",
        nombreEmergencia: "Patricia H",
        telefonoEmergencia: "918901235",
        institucion: "UOH",
      },
      {
        id: 13,
        nombre: "Josefa Antonia",
        primerApellido: "Navarro",
        segundoApellido: "Molina",
        rut: "20.888.999-0",
        correo: "j.navarro@uoh.cl",
        telefono: "919012345",
        nombreEmergencia: "Ricardo M",
        telefonoEmergencia: "919012346",
        institucion: "UOH",
      },
      {
        id: 14,
        nombre: "Cristóbal Andrés",
        primerApellido: "Rojas",
        segundoApellido: "Vargas",
        rut: "20.999.000-1",
        correo: "c.rojas@uoh.cl",
        telefono: "920123456",
        nombreEmergencia: "Andrea V",
        telefonoEmergencia: "920123457",
        institucion: "UOH",
      },
      {
        id: 15,
        nombre: "Daniela Sofía",
        primerApellido: "Gutiérrez",
        segundoApellido: "Sánchez",
        rut: "21.000.111-2",
        correo: "d.gutierrez@uoh.cl",
        telefono: "921234567",
        nombreEmergencia: "Luis S",
        telefonoEmergencia: "921234568",
        institucion: "UOH",
      },
    ],
  },
  {
    id: "NOM-2025-022",
    centroFormador: "AIEP",
    carrera: "Enfermería",
    fechaInicio: "15/10/2025",
    fechaTermino: "22/11/2025",
    numeroAlumnos: 4,
    tipoJornada: "Diurna",
    asignatura: "Cuidados del Adulto",
    estado: "En Curso",
    alumnosAsignados: [
      {
        id: 16,
        nombre: "Ignacio Javier",
        primerApellido: "Castillo",
        segundoApellido: "Cáceres",
        rut: "21.111.222-3",
        correo: "i.castillo@aiep.cl",
        telefono: "922345678",
        nombreEmergencia: "Marcela C",
        telefonoEmergencia: "922345679",
        institucion: "AIEP",
      },
      {
        id: 17,
        nombre: "Antonia Isidora",
        primerApellido: "Silva",
        segundoApellido: "Pizarro",
        rut: "21.222.333-4",
        correo: "a.silva@aiep.cl",
        telefono: "923456789",
        nombreEmergencia: "Javier P",
        telefonoEmergencia: "923456790",
        institucion: "AIEP",
      },
      {
        id: 18,
        nombre: "Benjamín Alonso",
        primerApellido: "Martínez",
        segundoApellido: "Araya",
        rut: "21.333.444-5",
        correo: "b.martinez@aiep.cl",
        telefono: "924567890",
        nombreEmergencia: "Claudia A",
        telefonoEmergencia: "924567891",
        institucion: "AIEP",
      },
      {
        id: 19,
        nombre: "Florencia Emilia",
        primerApellido: "López",
        segundoApellido: "Espinoza",
        rut: "21.444.555-6",
        correo: "f.lopez@aiep.cl",
        telefono: "925678901",
        nombreEmergencia: "Gonzalo E",
        telefonoEmergencia: "925678902",
        institucion: "AIEP",
      },
    ],
  },
  {
    id: "NOM-2025-030",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "27/10/2025",
    fechaTermino: "06/12/2025",
    numeroAlumnos: 3,
    tipoJornada: "Diurna",
    asignatura: "Procedimientos Básicos",
    estado: "Programada",
    alumnosAsignados: [
      {
        id: 20,
        nombre: "Vicente Tomás",
        primerApellido: "Reyes",
        segundoApellido: "Salazar",
        rut: "21.555.666-7",
        correo: "v.reyes@inacapmail.cl",
        telefono: "926789012",
        nombreEmergencia: "Paula S",
        telefonoEmergencia: "926789013",
        institucion: "INACAP",
      },
      {
        id: 21,
        nombre: "Martina Josefa",
        primerApellido: "Muñoz",
        segundoApellido: "Moreno",
        rut: "21.666.777-8",
        correo: "m.munoz@inacapmail.cl",
        telefono: "927890123",
        nombreEmergencia: "Rodrigo M",
        telefonoEmergencia: "927890124",
        institucion: "INACAP",
      },
      {
        id: 22,
        nombre: "Joaquín Esteban",
        primerApellido: "González",
        segundoApellido: "Riquelme",
        rut: "21.777.888-9",
        correo: "j.gonzalez@inacapmail.cl",
        telefono: "928901234",
        nombreEmergencia: "Teresa R",
        telefonoEmergencia: "928901235",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-001",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "03/03/2025",
    fechaTermino: "12/04/2025",
    numeroAlumnos: 2,
    tipoJornada: "Diurna",
    asignatura: "Salud del Adulto I",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 1,
        nombre: "Karla Estrella",
        primerApellido: "Labbé",
        segundoApellido: "Zúñiga",
        rut: "20.963.728-6",
        correo: "k.labbe@inacapmail.cl",
        telefono: "966599330",
        nombreEmergencia: "Susy Z",
        telefonoEmergencia: "989022154",
        institucion: "INACAP",
      },
      {
        id: 2,
        nombre: "Alexis Andrés",
        primerApellido: "Burgos",
        segundoApellido: "Rios",
        rut: "20.443.124-8",
        correo: "a.burgos@inacapmail.cl",
        telefono: "977947138",
        nombreEmergencia: "Rigoberto B",
        telefonoEmergencia: "933976968",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-015",
    centroFormador: "Universidad de O'Higgins",
    carrera: "Medicina",
    fechaInicio: "18/08/2025",
    fechaTermino: "27/09/2025",
    numeroAlumnos: 6,
    tipoJornada: "4 Turno",
    asignatura: "Internado Medicina Interna",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 10,
        nombre: "Diego Alejandro",
        primerApellido: "Torres",
        segundoApellido: "Silva",
        rut: "20.555.666-7",
        correo: "d.torres@uoh.cl",
        telefono: "916789012",
        nombreEmergencia: "María S",
        telefonoEmergencia: "916789013",
        institucion: "UOH",
      },
      {
        id: 11,
        nombre: "Fernanda Belén",
        primerApellido: "Morales",
        segundoApellido: "Reyes",
        rut: "20.666.777-8",
        correo: "f.morales@uoh.cl",
        telefono: "917890123",
        nombreEmergencia: "Jorge R",
        telefonoEmergencia: "917890124",
        institucion: "UOH",
      },
      {
        id: 12,
        nombre: "Tomás Eduardo",
        primerApellido: "Fuentes",
        segundoApellido: "Herrera",
        rut: "20.777.888-9",
        correo: "t.fuentes@uoh.cl",
        telefono: "918901234",
        nombreEmergencia: "Patricia H",
        telefonoEmergencia: "918901235",
        institucion: "UOH",
      },
      {
        id: 13,
        nombre: "Josefa Antonia",
        primerApellido: "Navarro",
        segundoApellido: "Molina",
        rut: "20.888.999-0",
        correo: "j.navarro@uoh.cl",
        telefono: "919012345",
        nombreEmergencia: "Ricardo M",
        telefonoEmergencia: "919012346",
        institucion: "UOH",
      },
      {
        id: 14,
        nombre: "Cristóbal Andrés",
        primerApellido: "Rojas",
        segundoApellido: "Vargas",
        rut: "20.999.000-1",
        correo: "c.rojas@uoh.cl",
        telefono: "920123456",
        nombreEmergencia: "Andrea V",
        telefonoEmergencia: "920123457",
        institucion: "UOH",
      },
      {
        id: 15,
        nombre: "Daniela Sofía",
        primerApellido: "Gutiérrez",
        segundoApellido: "Sánchez",
        rut: "21.000.111-2",
        correo: "d.gutierrez@uoh.cl",
        telefono: "921234567",
        nombreEmergencia: "Luis S",
        telefonoEmergencia: "921234568",
        institucion: "UOH",
      },
    ],
  },
  {
    id: "NOM-2025-022",
    centroFormador: "AIEP",
    carrera: "Enfermería",
    fechaInicio: "15/10/2025",
    fechaTermino: "22/11/2025",
    numeroAlumnos: 4,
    tipoJornada: "Diurna",
    asignatura: "Cuidados del Adulto",
    estado: "En Curso",
    alumnosAsignados: [
      {
        id: 16,
        nombre: "Ignacio Javier",
        primerApellido: "Castillo",
        segundoApellido: "Cáceres",
        rut: "21.111.222-3",
        correo: "i.castillo@aiep.cl",
        telefono: "922345678",
        nombreEmergencia: "Marcela C",
        telefonoEmergencia: "922345679",
        institucion: "AIEP",
      },
      {
        id: 17,
        nombre: "Antonia Isidora",
        primerApellido: "Silva",
        segundoApellido: "Pizarro",
        rut: "21.222.333-4",
        correo: "a.silva@aiep.cl",
        telefono: "923456789",
        nombreEmergencia: "Javier P",
        telefonoEmergencia: "923456790",
        institucion: "AIEP",
      },
      {
        id: 18,
        nombre: "Benjamín Alonso",
        primerApellido: "Martínez",
        segundoApellido: "Araya",
        rut: "21.333.444-5",
        correo: "b.martinez@aiep.cl",
        telefono: "924567890",
        nombreEmergencia: "Claudia A",
        telefonoEmergencia: "924567891",
        institucion: "AIEP",
      },
      {
        id: 19,
        nombre: "Florencia Emilia",
        primerApellido: "López",
        segundoApellido: "Espinoza",
        rut: "21.444.555-6",
        correo: "f.lopez@aiep.cl",
        telefono: "925678901",
        nombreEmergencia: "Gonzalo E",
        telefonoEmergencia: "925678902",  
        institucion: "AIEP",
      },
    ],
  },
  {
    id: "NOM-2025-030",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "27/10/2025",
    fechaTermino: "06/12/2025",
    numeroAlumnos: 3,
    tipoJornada: "Diurna",
    asignatura: "Procedimientos Básicos",
    estado: "Programada",
    alumnosAsignados: [
      {
        id: 20,
        nombre: "Vicente Tomás",
        primerApellido: "Reyes",
        segundoApellido: "Salazar",
        rut: "21.555.666-7",
        correo: "v.reyes@inacapmail.cl",
        telefono: "926789012",
        nombreEmergencia: "Paula S",
        telefonoEmergencia: "926789013",
        institucion: "INACAP",
      },
      {
        id: 21,
        nombre: "Martina Josefa",
        primerApellido: "Muñoz",
        segundoApellido: "Moreno",
        rut: "21.666.777-8",
        correo: "m.munoz@inacapmail.cl",
        telefono: "927890123",
        nombreEmergencia: "Rodrigo M",
        telefonoEmergencia: "927890124",
        institucion: "INACAP",
      },
      {
        id: 22,
        nombre: "Joaquín Esteban",
        primerApellido: "González",
        segundoApellido: "Riquelme",
        rut: "21.777.888-9",
        correo: "j.gonzalez@inacapmail.cl",
        telefono: "928901234",
        nombreEmergencia: "Teresa R",
        telefonoEmergencia: "928901235",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-001",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "03/03/2025",
    fechaTermino: "12/04/2025",
    numeroAlumnos: 2,
    tipoJornada: "Diurna",
    asignatura: "Salud del Adulto I",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 1,
        nombre: "Karla Estrella",
        primerApellido: "Labbé",
        segundoApellido: "Zúñiga",
        rut: "20.963.728-6",
        correo: "k.labbe@inacapmail.cl",
        telefono: "966599330",
        nombreEmergencia: "Susy Z",
        telefonoEmergencia: "989022154",
        institucion: "INACAP",
      },
      {
        id: 2,
        nombre: "Alexis Andrés",
        primerApellido: "Burgos",
        segundoApellido: "Rios",
        rut: "20.443.124-8",
        correo: "a.burgos@inacapmail.cl",
        telefono: "977947138",
        nombreEmergencia: "Rigoberto B",
        telefonoEmergencia: "933976968",
        institucion: "INACAP",
      },
    ],
  },
  {
    id: "NOM-2025-015",
    centroFormador: "Universidad de O'Higgins",
    carrera: "Medicina",
    fechaInicio: "18/08/2025",
    fechaTermino: "27/09/2025",
    numeroAlumnos: 6,
    tipoJornada: "4 Turno",
    asignatura: "Internado Medicina Interna",
    estado: "Finalizada",
    alumnosAsignados: [
      {
        id: 10,
        nombre: "Diego Alejandro",
        primerApellido: "Torres",
        segundoApellido: "Silva",
        rut: "20.555.666-7",
        correo: "d.torres@uoh.cl",
        telefono: "916789012",
        nombreEmergencia: "María S",
        telefonoEmergencia: "916789013",
        institucion: "UOH",
      },
      {
        id: 11,
        nombre: "Fernanda Belén",
        primerApellido: "Morales",
        segundoApellido: "Reyes",
        rut: "20.666.777-8",
        correo: "f.morales@uoh.cl",
        telefono: "917890123",
        nombreEmergencia: "Jorge R",
        telefonoEmergencia: "917890124",
        institucion: "UOH",
      },
      {
        id: 12,
        nombre: "Tomás Eduardo",
        primerApellido: "Fuentes",
        segundoApellido: "Herrera",
        rut: "20.777.888-9",
        correo: "t.fuentes@uoh.cl",
        telefono: "918901234",
        nombreEmergencia: "Patricia H",
        telefonoEmergencia: "918901235",
        institucion: "UOH",
      },
      {
        id: 13,
        nombre: "Josefa Antonia",
        primerApellido: "Navarro",
        segundoApellido: "Molina",
        rut: "20.888.999-0",
        correo: "j.navarro@uoh.cl",
        telefono: "919012345",
        nombreEmergencia: "Ricardo M",
        telefonoEmergencia: "919012346",
        institucion: "UOH",
      },
      {
        id: 14,
        nombre: "Cristóbal Andrés",
        primerApellido: "Rojas",
        segundoApellido: "Vargas",
        rut: "20.999.000-1",
        correo: "c.rojas@uoh.cl",
        telefono: "920123456",
        nombreEmergencia: "Andrea V",
        telefonoEmergencia: "920123457",
        institucion: "UOH",
      },
      {
        id: 15,
        nombre: "Daniela Sofía",
        primerApellido: "Gutiérrez",
        segundoApellido: "Sánchez",
        rut: "21.000.111-2",
        correo: "d.gutierrez@uoh.cl",
        telefono: "921234567",
        nombreEmergencia: "Luis S",
        telefonoEmergencia: "921234568",
        institucion: "UOH",
      },
    ],
  },
  {
    id: "NOM-2025-022",
    centroFormador: "AIEP",
    carrera: "Enfermería",
    fechaInicio: "15/10/2025",
    fechaTermino: "22/11/2025",
    numeroAlumnos: 4,
    tipoJornada: "Diurna",
    asignatura: "Cuidados del Adulto",
    estado: "En Curso",
    alumnosAsignados: [
      {
        id: 16,
        nombre: "Ignacio Javier",
        primerApellido: "Castillo",
        segundoApellido: "Cáceres",
        rut: "21.111.222-3",
        correo: "i.castillo@aiep.cl",
        telefono: "922345678",
        nombreEmergencia: "Marcela C",
        telefonoEmergencia: "922345679",
        institucion: "AIEP",
      },
      {
        id: 17,
        nombre: "Antonia Isidora",
        primerApellido: "Silva",
        segundoApellido: "Pizarro",
        rut: "21.222.333-4",
        correo: "a.silva@aiep.cl",
        telefono: "923456789",
        nombreEmergencia: "Javier P",
        telefonoEmergencia: "923456790",
        institucion: "AIEP",
      },
      {
        id: 18,
        nombre: "Benjamín Alonso",
        primerApellido: "Martínez",
        segundoApellido: "Araya",
        rut: "21.333.444-5",
        correo: "b.martinez@aiep.cl",
        telefono: "924567890",
        nombreEmergencia: "Claudia A",
        telefonoEmergencia: "924567891",
        institucion: "AIEP",
      },
      {
        id: 19,
        nombre: "Florencia Emilia",
        primerApellido: "López",
        segundoApellido: "Espinoza",
        rut: "21.444.555-6",
        correo: "f.lopez@aiep.cl",
        telefono: "925678901",
        nombreEmergencia: "Gonzalo E",
        telefonoEmergencia: "925678902",
        institucion: "AIEP",
      },
    ],
  },
  {
    id: "NOM-2025-030",
    centroFormador: "INACAP",
    carrera: "Tens",
    fechaInicio: "27/10/2025",
    fechaTermino: "06/12/2025",
    numeroAlumnos: 3,
    tipoJornada: "Diurna",
    asignatura: "Procedimientos Básicos",
    estado: "Programada",
    alumnosAsignados: [
      {
        id: 20,
        nombre: "Vicente Tomás",
        primerApellido: "Reyes",
        segundoApellido: "Salazar",
        rut: "21.555.666-7",
        correo: "v.reyes@inacapmail.cl",
        telefono: "926789012",
        nombreEmergencia: "Paula S",
        telefonoEmergencia: "926789013",
        institucion: "INACAP",
      },
      {
        id: 21,
        nombre: "Martina Josefa",
        primerApellido: "Muñoz",
        segundoApellido: "Moreno",
        rut: "21.666.777-8",
        correo: "m.munoz@inacapmail.cl",
        telefono: "927890123",
        nombreEmergencia: "Rodrigo M",
        telefonoEmergencia: "927890124",
        institucion: "INACAP",
      },
      {
        id: 22,
        nombre: "Joaquín Esteban",
        primerApellido: "González",
        segundoApellido: "Riquelme",
        rut: "21.777.888-9",
        correo: "j.gonzalez@inacapmail.cl",
        telefono: "928901234",
        nombreEmergencia: "Teresa R",
        telefonoEmergencia: "928901235",
        institucion: "INACAP",
      },
    ],
  },
];
