export type Capacidad = {
  id: number;
  servicio: string;
  carrera: string;
  nivelFormacion: string;
  tipoPractica: string;
  centroFormador: string;
  añoFormacion: string;
  tipoJornada: string;
  cupos: number;
};

export const data: Capacidad[] = [
  {
    id: 1,
    servicio: "Medicina",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "2º año",
    tipoJornada: "AM - PM",
    cupos: 6,
  },
  {
    id: 2,
    servicio: "Medicina",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "2º año",
    tipoJornada: "AM - PM",
    cupos: 6,
  },
  {
    id: 3,
    servicio: "Medicina",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "4º año",
    tipoJornada: "Diurno",
    cupos: 12,
  },
  {
    id: 4,
    servicio: "Medicina",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "6º año",
    tipoJornada: "Diurno",
    cupos: 10,
  },
  {
    id: 5,
    servicio: "Medicina",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad San Sebastián",
    añoFormacion: "7º año",
    tipoJornada: "Diurno",
    cupos: 10,
  },
  {
    id: 6,
    servicio: "Medicina",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "2º año",
    tipoJornada: "Diurno",
    cupos: 24,
  },
  {
    id: 7,
    servicio: "Medicina",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 1,
  },
  {
    id: 8,
    servicio: "Medicina",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "5º año",
    tipoJornada: "Diurno",
    cupos: 1,
  },
  {
    id: 9,
    servicio: "Medicina",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de O'Higgins",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 1,
  },
  {
    id: 10,
    servicio: "Pediatría",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Chile",
    añoFormacion: "3º año",
    tipoJornada: "AM - PM",
    cupos: 8,
  },
  {
    id: 11,
    servicio: "Pediatría",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Chile",
    añoFormacion: "3º año",
    tipoJornada: "Diurno",
    cupos: 10,
  },
  {
    id: 12,
    servicio: "Cirugía",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de Santiago",
    añoFormacion: "6º año",
    tipoJornada: "Diurno",
    cupos: 5,
  },
  {
    id: 13,
    servicio: "Cirugía",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de Santiago",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 2,
  },
  {
    id: 14,
    servicio: "Ginecología",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Valparaíso",
    añoFormacion: "4º año",
    tipoJornada: "AM - PM",
    cupos: 7,
  },
  {
    id: 15,
    servicio: "Ginecología",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Valparaíso",
    añoFormacion: "4º año",
    tipoJornada: "Diurno",
    cupos: 9,
  },
  {
    id: 16,
    servicio: "Psiquiatría",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de los Andes",
    añoFormacion: "7º año",
    tipoJornada: "Diurno",
    cupos: 3,
  },
  {
    id: 17,
    servicio: "Psiquiatría",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de los Andes",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 2,
  },
  {
    id: 18,
    servicio: "Traumatología",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad Católica",
    añoFormacion: "5º año",
    tipoJornada: "AM - PM",
    cupos: 6,
  },
  {
    id: 19,
    servicio: "Traumatología",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad Católica",
    añoFormacion: "5º año",
    tipoJornada: "Diurno",
    cupos: 8,
  },
  {
    id: 20,
    servicio: "Urgencias",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de Concepción",
    añoFormacion: "6º año",
    tipoJornada: "Diurno",
    cupos: 4,
  },
  {
    id: 21,
    servicio: "Urgencias",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de Concepción",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 2,
  },
  {
    id: 22,
    servicio: "Medicina Interna",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Magallanes",
    añoFormacion: "4º año",
    tipoJornada: "AM - PM",
    cupos: 7,
  },
  {
    id: 23,
    servicio: "Medicina Interna",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Magallanes",
    añoFormacion: "4º año",
    tipoJornada: "Diurno",
    cupos: 9,
  },
  {
    id: 24,
    servicio: "Anestesiología",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de Antofagasta",
    añoFormacion: "7º año",
    tipoJornada: "Diurno",
    cupos: 3,
  },
  {
    id: 25,
    servicio: "Anestesiología",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de Antofagasta",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 2,
  },
  {
    id: 26,
    servicio: "Dermatología",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Tarapacá",
    añoFormacion: "5º año",
    tipoJornada: "AM - PM",
    cupos: 5,
  },
  {
    id: 27,
    servicio: "Dermatología",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Curricular",
    centroFormador: "Universidad de Tarapacá",
    añoFormacion: "5º año",
    tipoJornada: "Diurno",
    cupos: 7,
  },
  {
    id: 28,
    servicio: "Oftalmología",
    carrera: "Medicina",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de la Frontera",
    añoFormacion: "6º año",
    tipoJornada: "Diurno",
    cupos: 4,
  },
  {
    id: 29,
    servicio: "Oftalmología",
    carrera: "Enfermería",
    nivelFormacion: "Pregrado",
    tipoPractica: "Internado",
    centroFormador: "Universidad de la Frontera",
    añoFormacion: "5º año",
    tipoJornada: "Cuarto Turno",
    cupos: 2,
  },
];
